name: Deploy to server

on: push

jobs:
    primer_job:
        runs-on: ubuntu-latest

        steps:
            - name: Generar archivo
              run: |
                echo "Archivo prueba, hola" >> test.log
      
            - name: Subir artefacto
              uses: actions/upload-artifact@v4
              with:
                name: archivo-test
                path: test.log

    segundo_job:
        runs-on: ubuntu-latest
        needs: primer_job

        steps:
            - name: Descargar artefacto
              uses: actions/download-artifact@v4
              with:
                name: archivo-test

            - name: Cat file
              run: cat test.log

    tercer_job:
        runs-on: ubuntu-latest
        env:
            HELLO: HOLA MUNDO

        outputs:
            salida: ${{ steps.step_3.outputs.my_variable }}

        steps:
            - name: Print environment variable
              id: step_3
              run: echo "my_variable==$HELLO" >> $GITHUB_ENV

            - name: Print environment variable
              run: echo "${{github.env.my_variable}}"

            - name: Print output variable
              run: echo "${{steps.step_3.outputs.my_variable}}"

    cuarto_job:
        runs-on: ubuntu-latest
        if: false

        steps:
            - name: Print message
              run: echo "This job will not run because the condition is false."